select FOOD_ORDER.PRODUCT_ID, PRODUCT_NAME, sum(FOOD_ORDER.AMOUNT* price) as TOTAL_SALES
from FOOD_PRODUCT join FOOD_ORDER 
on FOOD_PRODUCT.PRODUCT_ID= FOOD_ORDER.PRODUCT_ID
where year(PRODUCE_DATE) = 2022
and month(PRODUCE_DATE) = 5
group by (FOOD_ORDER.PRODUCT_ID)
order by TOTAL_SALES desc, PRODUCT_ID